### ISSUE TITLE
Agregar precio/costo en la tarea

### ISSUE THREAD

**Issue by jobiols** [jobiols/cl-vhing#12]
- Al validar una orden de venta se crean las tareas dentro de un proyecto, se debe copiar a la tarea el precio de venta que pusieron en la orden de venta, en un campo **precio de venta**
- Agregar un campo **precio de costo** en la tarea

**Comment by jobiols** [comment]
Ya se puede ver el precio y el costo en la tarea, ademas por conveniencia agregue el producto que la genera.

**Comment by ferheredia** [comment]
el precio de venta no se vé en la tarea, agregar
