### ISSUE TITLE
Número de cliente

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#17]
los contactos, del tipo compañía principalmente, deberían poder introducirles un número de cliente de 5 cifras que es lo que actualmente identifica un cliente y luego sus proyectos

**Comment by jobiols** [comment]
En los contactos tipo compañia hay una referencia que esta debajo del nombre, solo se ve cuando editas el contacto. Fijate si eso te sirve.

![screenshot-18 222 44 31-2018 10 09-17-52-43](https://user-images.githubusercontent.com/8525908/46698013-5c88f500-cbec-11e8-9446-898f46321804.png)

**Comment by ferheredia** [comment]
genial, creo que sirve. Este número no debería tener repeticiones. Actualmente lo hago con un planilla excel que me hace una cuenta para ver que ningún número nuevo tenga una diferencia 0 con ninguno de los anteriores. Se puede hacer algo así? y por otro lado quiero que se vea en las tarjetas de contactos y en el listado de contactos. Viendo estas cosas que son simples pero imagino tediosas para vos, cómo se te ocurre que nos conviene manejarnos para no ser molestos y al mismo tiempo afinar los detalles que queremos? será que podríamos editar nosotros las cosas con algunas recomendaciones? con el odoo studio, por ejemplo?

**Comment by jobiols** [comment]
Para que el numero no se repita y se genere solo, hay que crear una secuencia y relacionarla con ese campo. En ese caso dejaria la referencia como esta y crearia otro campo que read only para eso.
luego se puede poner en las tarjetas y en donde quieras.

No creo que puedan modificar estas cosas ustedes, el odoo studio es version Enterprise ademas no me simpatiza (como decia el chavo) porque el codigo que genera es incomprensible para los humanos.

Lo que habria que hacer es priorizar y definir que cosas necesitas para arrancar y dejar el resto para segunda etapa. Hay un proyecto que se llama segunda etapa se pueden mover los issues para alla. (esta sobre el menu de la derecha)

**Comment by ferheredia** [comment]
el número me gustaría elegirlo yo, si no se puede, vemos cómo hacer. De todos modos lo pasamos para la segunda etapa. No pude hacerlo yo este movimiento

**Comment by jobiols** [comment]
Se define como un numero entero que no se puede repetir, Luego ese numero de cliente junto con la fecha de creacion del presupuesto (AAAAMMDD) se debe poner como nombre de la cuenta analitica.

**Comment by jobiols** [comment]
El nro de referencia de cliente ya no se puede repetir, si hay repetidos ocurrira que si se edita el registro no se podrá salvar a menos que se cambie la referencia.
