### ISSUE TITLE
Project manager

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#18]
algo que me parece que no hablamos es que una cosa es quien hace cada tarea y otra es quien se hace cargo del proyecto como PM o leader. Cuando hablamos de asignar, siempre lo tratamos como a un colaborador, pero nunca hablamos de quién de nosotros dos (Julián o yo) seguiría el proceso

**Comment by ferheredia** [comment]
veo que en los ajustes del proyecto se puede asignar un responsable al proyecto. Lo que parece importante es poder ver el responsable del proyecto y el nombre de la obra en la pantalla de proyectos

**Comment by jobiols** [comment]
El responsable del proyecto es el que lo crea, y se puede cambiar.
El responsable y el nombre de la obra se ven en la vista de proyectos Proyecto / Configuracion / Proyectos

**Comment by jobiols** [comment]
Cierro porque considero cumplida la premisa
