### ISSUE TITLE
Facturación

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#19]
no puedo introducir el tipo de documento como FACTURA A.
Cómo manejo el número del punto de venta?
quiero pronto introducir las facturas ya hechas para poder registrar los deudores por ventas

**Comment by ferheredia** [comment]
veo que algún cliente muestra automáticamente el tipo de factura que se le debe emitir, pero la gran mayoría no muestra ni permite elegir nada

**Comment by jobiols** [comment]
Odoo define que tipo de documento en funcion de la posicion ante el iva de tu empresa y de la del partner. Seguramente no tenes definido eso en el partner.
Avisame si esta ok asi cierro el issue.

**Comment by ferheredia** [comment]
me falta saber cómo definirlo en los clientes, algunos cuando actualizo desde la AFIP no cambia nada, no sé si es eso o tiene algo más

**Comment by jobiols** [comment]
Por alguna misteriosa razón que desconozco la afip no actualiza la
responsabilidad.
Le tenes que poner a mano responsable inscripto.

Enviado desde mi samsung
