### ISSUE TITLE
partes de horas

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#20]
cuando quiero cargar horas me pide que introduzca el nombre del empleado, pero no me deja poner el mismo nombre de la persona que está asignada. Te diría que este campo no me sirve porque sería redundante. En el parte de horas aparece el nombre de la persona a la que está asignada la tarea, por lo que no veo por qué habría que introducirlo de nuevo. Aparte de eso, el dato es obligatorio, además de la descripción. Al menos te pido que estos datos no sean obligatorios.

**Comment by jobiols** [comment]
Al cargar horas en timesheet solo aparece el usuario asignado a la tarea, que ademas puede cambiar o sea una tarea puede fraccionarse y facturarse a varios proveedores.
Ademas tildando las horas cargadas de pueden mandar a facturar.
