### ISSUE TITLE
time sheet

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#24]
Columnas para el listado de partes de horas

- Fecha
- Empleado (o lo que sea)
- Descripción (sólo si entra)
- Proyecto (número)
- Cliente
- Nombre de la obra
- Tarea
- Horas

Estos partes de horas deberían ser filtrables entre: facturados, facturables

seleccionando los partes de horas que yo quiera, debería poder hacer una factura u orden de compra (lo que yo llamo orden de pago)

**Comment by jobiols** [comment]
Se agregaron todos los campos menos Descripcion, Se agrego un campo mas Purchase order como link que puede llevar a la orden de compra con la que se compraron estas horas.
Se agrego un filtro para mostrar las horas que no tienen orden de compra.
