### ISSUE TITLE
parte de horas

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#33]
desde la aplicación PARTES DE HORAS no puedo cargar horas, o más bien, puedo agregar partes pero no puedo agregarle horas
Quisiera poder acceder también desde esta parte, porque si no, sólo puedo acceder desde PROYECTOS

**Comment by ferheredia** [comment]
cuando facturo las horas, hago el envío de mail pero no sale

**Comment by ferheredia** [comment]
seguís como el único proveedor

**Comment by ferheredia** [comment]
cuando facturo las horas de los colaboradores hay una secuencia medio confusa de quién puede facturar horas, te lo tendría que explicar. Básicamente, para poder facturar horas debo crear usuarios y estos usuarios y son, por otro lado contactos, cómo manejar eso?
además los colaboradores que registramos como miembros de VH aparecen como vinculados a la compañía VH entonces no pueden hacer Factura C. Lo que hice fue crear un usuario nuevo: Nicolás Diez y lo puse como MONOTRIBUTISTA, no lo vinculé a la empresea VH y pude facturar

**Comment by ferheredia** [comment]
cuando quiero facturar horas de colaboradores no tengo información para determinar el valor unitario de la hora. Es decir, en el parte de horas cargué al avance, voy a solicitud de presupuestos y para obtener el precio tengo que volver a la tarea específica para ver cuál era el precio de compra que le había definido

**Comment by ferheredia** [comment]
en la planilla donde se ven todos los partes de horas que existen, como para facturar por ejemplo, debería aparecer el monto a pagar en cada línea antes o en vez de la cantidad de horas correspondientes

**Comment by ferheredia** [comment]
debería poder ordenar por colaborador. Esto ya lo pedí en otra parte porque en general las tablas no pueden ordenarse por varios de los campos que tienen

**Comment by jobiols** [comment]
en la planilla donde se ven todos los partes de horas que existen, como para facturar por ejemplo, debería aparecer el monto a pagar en cada línea antes o en vez de la cantidad de horas correspondientes
