### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#35]
no consigo sincronizar porque la dirección de la base de datos es un IP. Tenés experiencia con esto? Sólo comentame, ya hice todo el proceso pero me trabo en eso. No acepta un URL como IP pública como es nuestro caso

**Comment by jobiols** [comment]
Si lo que hay que hacer es definir un dominio y delegarlo a la ip vos ya
tenes un sitio web?

Enviado desde mi samsung

**Comment by ferheredia** [comment]
tengo un sitio web, si
www.vhingenieria.com
lo otro no lo entiendo, si me das otro dato lo podría hablar con la persona que nos mantiene la página

**Comment by jobiols** [comment]
Ok si tenes un sitio es mas facil, se puede agregar un subdominio.
Quedaría algo as:
odoo.vhing.com
Suponiendo que tu sitio es vhing.com

Enviado desde mi samsung

**Comment by ferheredia** [comment]
actualmente el dominio odoo.vhingenieria.com dirige al IP de nuestra base de datos, pero google sigue pidiendo una url para autenticar. Me gustaría resolverlo este año esto, sin apuro

**Comment by jobiols** [comment]
Hola.

Acabo de firmar la petición ".@Alferdez @SantiCafiero @ginesggarcia
@msalnacion: LOS MÉDICOS NECESITAMOS TU FIRMA MÁS QUE TU APLAUSO Para el
DNU que nos proteja..." y pensé que te podría interesar.

Estamos intentando conseguir 150.000 firmas y necesitamos todo el apoyo que
podamos conseguir. Puedes leer más y firmar la petición aquí:

http://chng.it/KHYcv4ZHP7

¡Gracias!
Jorge
