### ISSUE TITLE
cuenta analítica

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#37]
el nombre de la cuenta analítica es el código del proyecto, y se le debe agregar como referencia el nombre de la obra. Veo que automáticamente se agrega el nombre del cliente.

**Comment by jobiols** [comment]
Revisar constraint en campo nombre de la cuenta analitica, da un warning en update all.

**Comment by ferheredia** [comment]
veo que la cuenta analítica se genera automaticamente pero hay un error: actualmente aparece el número del proyecto (que a su vez se compone por el número de cliente y la fecha del presupuesto) - el número del cliente - y el nombre del cliente.
Me da la impresión que cuando agregaste el campo referencia, se agregó la referencia del cliente, y no la referencia de la obra, es decir, en vez de repetir el número del cliente, debería aparecer el campo WORK
