### ISSUE TITLE
depósito de cheques

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#46]
tenía unos cheques cuando empezamos a usar esto y no supe cómo manejarlos
el lunes me van a dar otro cheque y cuando lo deposite no sé cómo hacer para registrarlo mediante
TRANSFERENCIAS

**Comment by jobiols** [comment]
Si te pagan con un cheque tenes que usar el medio de pago cheques de terceros, ahi aparecen los campos para cargar los datos del cheque.
El cheque queda en cartera, podes pagar algo con ese cheque o cuando llega el dia del deposito lo marcas como depositado y se acredita en la cuenta bancaria.
