### ISSUE TITLE
presupuestos

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#51]
cómo puedo archivar los presupuestos que no voy a querer ver tanto? como cuando termino una obra?

**Comment by jobiols** [comment]
Ahí no tenes botón de archivar. Te muestra ordenado por fecha último arriba
con lo que ves los últimos.
Podrías poner un filtro por defecto que seleccione el último mes.

**Comment by ferheredia** [comment]
en el listado de presupuestos nos gustaría más bien ver el precio sin impuestos, porque cada proyecto tiene diferentes % de IVA y nos confunde

**Comment by ferheredia** [comment]
se podrían generar más categorías de estado? lo puedo hacer yo? Nos gustaría filtrar por criterios que no están.
La lista de estados si pudiera editarse sería:
Presupuesto (existe)
Presupuesto enviado (existe)
Pedido de venta (existe)
Cancelado (existe)
Cobrado
Duplicado

**Comment by jobiols** [comment]
Ver este tema
en el listado de presupuestos nos gustaría más bien ver el precio sin impuestos, porque cada proyecto tiene diferentes % de IVA y nos confunde
