### ISSUE TITLE
en la planilla donde se ven todos los partes de horas que existen, como para facturar por ejemplo, debería aparecer el monto a pagar en cada línea antes o en vez de la cantidad de horas correspondientes

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#54]
en la planilla donde se ven todos los partes de horas que existen, como para facturar por ejemplo, debería aparecer el monto a pagar en cada línea antes o en vez de la cantidad de horas correspondientes

_Originally posted by @ferheredia in https://github.com/jobiols/cl-vhing/issues/33#issuecomment-446380900_

**Comment by ntsystemwork** [comment]
corregido

**Comment by ferheredia** [comment]
habría que sumar los subtotales a pagar a cada colaborador y el total a pagar de todos

**Comment by jobiols** [comment]
correr migracion para borrar columna amount y que la recalcule. 11.0.0.0.7
