### ISSUE TITLE
tareas - progreso %

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#55]
aparece 100% pero estaba al 60%
o incluso 0%
![](https://cdn.discordapp.com/attachments/428994146842181655/540536110141538309/unknown.png)

**Comment by ferheredia** [comment]
el precio unitario de las tareas surge de dividir el COST PRICE / 100
necesitamos que el precio unitario surja de la cuenta COST PRICE / HORAS INICIALES PLANIFICADAS
porque hay proyectos que sí los menejamos por horas y otros que no.

**Comment by jobiols** [comment]
corregido
