### ISSUE TITLE
comparar cuentas

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#56]
quisiera tener una vista de la diferencia entre dos cuentas.
En este caso son las cuentas de adelanto de resultados de julián y mía
1.2.02.01.041
1.2.02.01.040

**Comment by ferheredia** [comment]
necesitamos una manera simple de ver en cada proyecto el costo y el ingreso junto con un resultado de cada proyecto.
También queremos que estos datos se puedan graficar de manera global para tener idea de los rendimientos definidos en el tiempo que querramos.

**Comment by jobiols** [comment]
Se puede ver la diferencia entre cuentas en Facturacion / Asesor / Revisar socios.
