### ISSUE TITLE
Actividades hechas

### ISSUE THREAD

**Issue by ferheredia** [jobiols/cl-vhing#61]
cuando se realizan las actividades aparecen como Realizadas por Servicio Técnico en vez de la persona que realmente lo hizo

**Comment by jobiols** [comment]
Ejemplo, dice hecho por soporte tecnico:
![b7467e9c-6e0c-449d-826e-72863485a857](https://user-images.githubusercontent.com/8525908/59935756-e5675a00-9424-11e9-8182-a2bd3870988c.jpeg)

Aparentemente hay un sudo() que fuerza el ownership de la nota.

**Comment by jobiols** [comment]
La nota que pone es bastante difícil de seguir ubicar ya que usa el sistema de mensajeria interna y obviamente es un bug de odoo considero que no vale la pena corregirlo.
