### ISSUE TITLE
Nombre proyecto => nro de proyecto

### ISSUE THREAD

**Issue by jobiols** [jobiols/cl-vhing#8]
En la vista de proyectos cambiar el label Nombre Proyecto

**Comment by ferheredia** [comment]
al momento de cambiar el nombre del proyecto, o más bien, ponerle el nombre al proyecto, quisiera tener los datos a la vista. Es decir, fecha de creación de la oferta y número de cliente. Caso contrario es muy incómodo rastrear los datos. Si esto se pudiera poner automáticamente sería genial, pero no pido tanto

**Comment by ferheredia** [comment]
en el tablero de proyectos, las tarjetas deberían tener el nombre de la obra y sería bueno ver el % de avance del proyecto
